
name: Node.js CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Validate dist
      run: |
        npm i -g ncc
        ncc build src/index.ts -o dist2;
        diff dist/index.js dist2/index.js
        if [ $? -ne 0 ]; then
          echo "Files differ!"
          exit 1
        fi